In [ ]:
# Importing libraries

In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
df.count()

Row ID           9994
Order ID         9994
Order Date       9994
Ship Date        9994
Ship Mode        9994
Customer ID      9994
Customer Name    9994
Segment          9994
Country          9994
City             9994
State            9994
Postal Code      9994
Region           9994
Product ID       9994
Category         9994
Sub-Category     9994
Product Name     9994
Sales            9994
Quantity         9994
Discount         9994
Profit           9994
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [9]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

---

### Group By the df

In [10]:
# df1 - order summary

df1 = df.groupby('Order ID').agg(
    total_sales = ('Sales','sum'),
    total_profit = ('Profit', 'sum')
).reset_index()

In [13]:
df1

            Order ID  total_sales  total_profit
0     CA-2014-100006      377.970      109.6113
1     CA-2014-100090      699.192      -19.0890
2     CA-2014-100293       91.056       31.8696
3     CA-2014-100328        3.928        1.3257
4     CA-2014-100363       21.376        7.7192
...              ...          ...           ...
5004  US-2017-168802       18.368        5.9696
5005  US-2017-169320      171.430       16.6721
5006  US-2017-169488       56.860       26.5552
5007  US-2017-169502      113.410       32.4527
5008  US-2017-169551     1344.838      -62.2895

[5009 rows x 3 columns]

In [14]:
df1.head()

         Order ID  total_sales  total_profit
0  CA-2014-100006      377.970      109.6113
1  CA-2014-100090      699.192      -19.0890
2  CA-2014-100293       91.056       31.8696
3  CA-2014-100328        3.928        1.3257
4  CA-2014-100363       21.376        7.7192

In [18]:
# df2 - customer info per order

df2 = df[['Order ID', 'Customer Name', 'Segment', 'Region']].drop_duplicates()

In [19]:
df2

            Order ID     Customer Name    Segment Region
0     CA-2016-152156       Claire Gute   Consumer  South
2     CA-2016-138688   Darrin Van Huff  Corporate   West
3     US-2015-108966    Sean O'Donnell   Consumer  South
5     CA-2014-115812   Brosina Hoffman   Consumer   West
12    CA-2017-114412      Andrew Allen   Consumer  South
...              ...               ...        ...    ...
9986  CA-2016-125794      Maris LaWare   Consumer   West
9987  CA-2017-163629      Ruben Ausman  Corporate  South
9989  CA-2014-110422  Tom Boeckenhauer   Consumer  South
9990  CA-2017-121258       Dave Brooks   Consumer   West
9993  CA-2017-119914      Chris Cortes   Consumer   West

[5009 rows x 4 columns]

---

### Q1. Merge df1 and df2 on Order ID (inner join)

In [32]:
merge = pd.merge(df1,df2, on='Order ID', how='inner')
merge

,Order ID,total_sales,total_profit,Customer Name,Segment,Region
0,CA-2014-100006,377.970,109.6113,Dennis Kane,Consumer,East
1,CA-2014-100090,699.192,-19.0890,Ed Braxton,Corporate,West
2,CA-2014-100293,91.056,31.8696,Neil Französisch,Home Office,South
3,CA-2014-100328,3.928,1.3257,Jasper Cacioppo,Consumer,East
4,CA-2014-100363,21.376,7.7192,Jim Mitchum,Corporate,West
...,...,...,...,...,...,...
5004,US-2017-168802,18.368,5.9696,Jack O'Briant,Corporate,West
5005,US-2017-169320,171.430,16.6721,Lena Hernandez,Consumer,Central
5006,US-2017-169488,56.860,26.5552,Allen Armold,Consumer,East
5007,US-2017-169502,113.410,32.4527,Matthew Grinstein,Home Office,Central
5008,US-2017-169551,1344.838,-62.2895,Rob Lucas,Consumer,East

In [34]:
merge.shape

(5009, 6)

### Q2. Check for missing values in the merged result

In [29]:
merge.isnull().sum()

Order ID         0
total_sales      0
total_profit     0
Customer Name    0
Segment          0
Region           0
dtype: int64

### Q3. If any missing — fill with appropriate values

In [36]:
merge['Customer Name'].fillna('Unknown', inplace=True)
merge['total_sales'].fillna(0,inplace=True)

C:\Users\tejas\AppData\Local\Temp\ipykernel_16628\2594537742.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merge['Customer Name'].fillna('Unknown', inplace=True)

In [37]:
merge['Customer Name'] = merge['Customer Name'].fillna('Unknown')
merge['total_sales'] = merge['total_sales'].fillna(0)

### Q4. How many orders exist in df1 but NOT in df2? (left anti join)

In [40]:
left_join = pd.merge(df1,df2, on='Order ID', how='left')
left_join

,Order ID,total_sales,total_profit,Customer Name,Segment,Region
0,CA-2014-100006,377.970,109.6113,Dennis Kane,Consumer,East
1,CA-2014-100090,699.192,-19.0890,Ed Braxton,Corporate,West
2,CA-2014-100293,91.056,31.8696,Neil Französisch,Home Office,South
3,CA-2014-100328,3.928,1.3257,Jasper Cacioppo,Consumer,East
4,CA-2014-100363,21.376,7.7192,Jim Mitchum,Corporate,West
...,...,...,...,...,...,...
5004,US-2017-168802,18.368,5.9696,Jack O'Briant,Corporate,West
5005,US-2017-169320,171.430,16.6721,Lena Hernandez,Consumer,Central
5006,US-2017-169488,56.860,26.5552,Allen Armold,Consumer,East
5007,US-2017-169502,113.410,32.4527,Matthew Grinstein,Home Office,Central
5008,US-2017-169551,1344.838,-62.2895,Rob Lucas,Consumer,East

In [41]:
not_in_df2 = left_join[left_join['Customer Name'].isnull()]

In [42]:
not_in_df2

Empty DataFrame
Columns: [Order ID, total_sales, total_profit, Customer Name, Segment, Region]
Index: []

In [43]:
print(f"Orders only in df1: {len(not_in_df2)}")

Orders only in df1: 0

In [44]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object